FORMAT: 1A

# Accounts

## Customers [/customers]

### Get customers [GET]

+ Response 200 (application/json)

    + Body

            {
            "_embedded" : {
                "customer" : [ {
                "firstName" : "Eve",
                "lastName" : "Berger",
                "username" : "Eve_Berger",
                "_links" : {
                    "self" : {
                    "href" : "http://accounts/customers/5791fea0c14e0679940fdda6"
                    },
                    "customer" : {
                    "href" : "http://accounts/customers/5791fea0c14e0679940fdda6"
                    },
                    "addresses" : {
                    "href" : "http://accounts/customers/5791fea0c14e0679940fdda6/addresses"
                    },
                    "cards" : {
                    "href" : "http://accounts/customers/5791fea0c14e0679940fdda6/cards"
                    }
                }
                }, {
                "firstName" : "User",
                "lastName" : "Name",
                "username" : "user",
                "_links" : {
                    "self" : {
                    "href" : "http://accounts/customers/5791fea0c14e0679940fdda9"
                    },
                    "customer" : {
                    "href" : "http://accounts/customers/5791fea0c14e0679940fdda9"
                    },
                    "addresses" : {
                    "href" : "http://accounts/customers/5791fea0c14e0679940fdda9/addresses"
                    },
                    "cards" : {
                    "href" : "http://accounts/customers/5791fea0c14e0679940fdda9/cards"
                    }
                }
                }, {
                "firstName" : "User1",
                "lastName" : "Name1",
                "username" : "user1",
                "_links" : {
                    "self" : {
                    "href" : "http://accounts/customers/5791fea0c14e0679940fddac"
                    },
                    "customer" : {
                    "href" : "http://accounts/customers/5791fea0c14e0679940fddac"
                    },
                    "addresses" : {
                    "href" : "http://accounts/customers/5791fea0c14e0679940fddac/addresses"
                    },
                    "cards" : {
                    "href" : "http://accounts/customers/5791fea0c14e0679940fddac/cards"
                    }
                }
                } ]
            },
            "_links" : {
                "self" : {
                "href" : "http://accounts/customers"
                },
                "profile" : {
                "href" : "http://accounts/profile/customers"
                },
                "search" : {
                "href" : "http://accounts/customers/search"
                }
            },
            "page" : {
                "size" : 20,
                "totalElements" : 3,
                "totalPages" : 1,
                "number" : 0
            }
            }


## Cards [/cards]

### Get cards [GET]

+ Response 200 (application/json)

    + Body

            {
            "_embedded" : {
                "card" : [ {
                "longNum" : "2525794243749791",
                "expires" : "08/19",
                "ccv" : "445",
                "_links" : {
                    "self" : {
                    "href" : "http://accounts/cards/5791fea0c14e0679940fdda5"
                    },
                    "card" : {
                    "href" : "http://accounts/cards/5791fea0c14e0679940fdda5"
                    }
                }
                }, {
                "longNum" : "2189320572309549",
                "expires" : "08/19",
                "ccv" : "723",
                "_links" : {
                    "self" : {
                    "href" : "http://accounts/cards/5791fea0c14e0679940fdda8"
                    },
                    "card" : {
                    "href" : "http://accounts/cards/5791fea0c14e0679940fdda8"
                    }
                }
                }, {
                "longNum" : "8406318488029178",
                "expires" : "08/19",
                "ccv" : "287",
                "_links" : {
                    "self" : {
                    "href" : "http://accounts/cards/5791fea0c14e0679940fddab"
                    },
                    "card" : {
                    "href" : "http://accounts/cards/5791fea0c14e0679940fddab"
                    }
                }
                } ]
            },
            "_links" : {
                "self" : {
                "href" : "http://accounts/cards"
                },
                "profile" : {
                "href" : "http://accounts/profile/cards"
                }
            },
            "page" : {
                "size" : 20,
                "totalElements" : 3,
                "totalPages" : 1,
                "number" : 0
            }
            }

## Addresses [/addresses]

### List [GET]

+ Response 200 (application/json)

    + Body

            {
            "_embedded" : {
                "address" : [ {
                "number" : "5",
                "street" : "Mossywood Road",
                "city" : "Glasgow",
                "postcode" : "G68 9DX",
                "country" : "United Kingdom",
                "_links" : {
                    "self" : {
                    "href" : "http://accounts/addresses/5791fea0c14e0679940fdda4"
                    },
                    "address" : {
                    "href" : "http://accounts/addresses/5791fea0c14e0679940fdda4"
                    }
                }
                }, {
                "number" : "2",
                "street" : "Trickett Close",
                "city" : "Hope Valley",
                "postcode" : "S33 8WR",
                "country" : "United Kingdom",
                "_links" : {
                    "self" : {
                    "href" : "http://accounts/addresses/5791fea0c14e0679940fdda7"
                    },
                    "address" : {
                    "href" : "http://accounts/addresses/5791fea0c14e0679940fdda7"
                    }
                }
                }, {
                "number" : "5",
                "street" : "Mossywood Road",
                "city" : "Glasgow",
                "postcode" : "G68 9DX",
                "country" : "United Kingdom",
                "_links" : {
                    "self" : {
                    "href" : "http://accounts/addresses/5791fea0c14e0679940fddaa"
                    },
                    "address" : {
                    "href" : "http://accounts/addresses/5791fea0c14e0679940fddaa"
                    }
                }
                } ]
            },
            "_links" : {
                "self" : {
                "href" : "http://accounts/addresses"
                },
                "profile" : {
                "href" : "http://accounts/profile/addresses"
                }
            },
            "page" : {
                "size" : 20,
                "totalElements" : 3,
                "totalPages" : 1,
                "number" : 0
            }
            }