FORMAT: 1A

# Carts and items 


## Customer cart [/carts/{customerId}]

### Get cart [GET]

+ Response 200 (application/json)
    + Body

            {"customerId":1}

### Delete cart [DELETE]

+ Response 200

### Merge cart [/carts/{customerId}/merge{?sessionId}]

+ Parameter
    + sessionId (string, required)


## Cart items [/carts/{customerId}/items]

+ Response 200 (application/json)
    + Attributes (array[Item])


### Add an item to the cart [POST]

+ Request (application/json)
    + Attributes (Item)

+  Response 201

### Update item [PATCH]

+ Request (application/json)
    + Attributes (Item)

+ Response 202

## Cart item [/carts/{customerId}/items/{itemId}]

### Delete [DELETE]

+ Parameters
    + itemId (string, required)

+ Response 202


# Data Structures

## Item (object)
    + itemId: (string)
    + quantity: 20 (number)
    + unitPrice: 20.0 (number)
