FORMAT: 1A

# Payment resources

## Authorisation [/paymentAuth]

### Authorise [POST]

+ Attributes (Authorisation)

+ Request (application/json)

+ Response 200 (application/json)

    + Body

            {"authorised":true}

# Data Structures

## Authorisation (object)

+ amount: 20 (number)